- layouts/blog.js
- layouts/search.js
- lib/notion.js
- pages/index.js
- pages/tag/[tag].js
🐛 Fix deploy error when socialLink is not defined
🐛 Fix deploy error when tag does not exist
> Fix deployment failure due to edge cases

- components/BlogPost.js
- components/Container.js
- components/Footer.js
- components/Pagination.js
- components/Tags.js
- layouts/blog.js
- lib/formatDate.js
- lib/notion.js
- pages/[slug].js
- pages/feed.js
- pages/index.js
- pages/page/[page].js
- pages/search.js
- pages/tag/[tag].js
- styles/globals.css
> :mag: Improve SEO and organize code

- blog.config.js
- lib/ackee.js
- package-lock.json
- package.json
- pages/_app.js
- pages/_document.js
> :chart_with_upwards_trend: Add ackee analytics

- blog.config.js
- components/Gtag.js
- lib/gtag.js
- pages/_app.js
- pages/_document.js
Add Google Analytics as an option to track your blog
> :chart_with_upwards_trend: Add Google Analytics as an option

- components/Header.js
Set the alt of logo as the correct BLOG.author, dynamically.
> [Customization] Correct the value of alt

- components/Tags.js
- layouts/blog.js
- layouts/search.js
- styles/globals.css
`[Appearance]` Add &nbsp; before each tag in posts
`[Appearance]` Fix: wrap tags in posts
`[Appearance]` Hide scrolling bar in tag list in search
`[Appearance]` Search box & article container in search
`[Appearance]` Tag margin, border, color, selected in search
> [Appearance] Search layout and tag appearance

- styles/globals.css
To forbid selecting tag text in the search page
> [UX] Tag text selection forbidden

- components/Footer.js
> :bug: Fix footer error

- package.json
- yarn.lock
> Upgrade package.json

- blog.config.js
- public/robots.txt
> Revert "Site"

- tailwind.config.js
> Fix issue #90

- layouts/default.js
- layouts/fullwidth.js
> Fix Date Bug

- layouts/default.js
> Small Bug Fix

- blog.config.js
- components/BlogPost.js
- layouts/default.js
- layouts/fullwidth.js
- lib/notion/getAllPosts.js
- lib/notion/getPageProperties.js
- lib/rss.js
This PR fix sort by date not working
This PR also fix deployment error if there's an item in nobelium database doesn't meet requirements
#102
> :bug: Fix sort by date not working & more

- blog.config.js
- pages/_document.js
The automatically collapsed navigation bar
> [Feature] Allow autoCollapsedNavBar

- components/Header.js
- components/TagItem.js
- components/Tags.js
- layouts/default.js
- layouts/fullwidth.js
- layouts/search.js
Thank you for develop awesome blog system 💯
I sent PR for the following reasons:
1. The tag link was implemented with click event on non-interactive content.
-> fixed link to use next/router for accessibility
- (enter tab & on key press...)
- FYI: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md
2. The style of selected tag was not applied on search page.
3. (New) Header logo was not wrapped with `a` tag
|Before|After|
|---|---|
|https://nobelium.vercel.app/tag/Sociology|https://nobelium-ge7u39giu-yokinist.vercel.app/tag/Sociology|
|[![Image from Gyazo](https://i.gyazo.com/bb712eaa23a842191f24527e712fb9dd.gif)](https://gyazo.com/bb712eaa23a842191f24527e712fb9dd)|[![Image from …
> fix(a11y): tag link & header logo link

- blog.config.js
- pages/_app.js
I found that analytics is not enabled 👀
- Fix read analytics-provider key: `analytics` -> `analytics.provider`
- Disable analytics in development environment
> fix: analytics provider

- blog.config.js
- lib/lang.js
- lib/locale.js
> i18n: add ja-JP lang support

- .eslintrc.js
- next-sitemap.config.js
- next-sitemap.js
- package.json
- yarn.lock
- generate sitemap.xml & robots.txt after build with [next-sitemap](https://github.com/iamvishnusankar/next-sitemap#readme)
> feat: generate sitemap and robots txt 

- blog.config.js
- lib/lang.js
Add es-ES (Spanish) lang support.
This is my first time creating a PR, so I hope I am not doing anything wrong 😅.
> Add es-ES lang support

- styles/notion.css
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/19779874/132491162-2e1a5a23-506f-4399-be4c-56d08311d9a6.png)|![image](https://user-images.githubusercontent.com/19779874/132555068-549a6ae9-0ffb-4b7e-99dc-58d904001d95.png)|
|![image](https://user-images.githubusercontent.com/19779874/132554829-3dad23ca-09b9-408b-ba86-7f421a6ee2b6.png)|![image](https://user-images.githubusercontent.com/19779874/132554851-4e5c9cf2-ec36-40a9-9044-56a1d815ea53.png)|
> 🎨 Minor tweaks for style

- components/BlogPost.js
- components/Header.js
- components/Tags.js
- components/Vercel.js
> fix: a11y issues

- layouts/layout.js
- styles/notion.css
close: https://github.com/craigary/nobelium/issues/179
[![Image from Gyazo](https://i.gyazo.com/003da39483d5db4cd82ec68edf875eda.gif)](https://gyazo.com/003da39483d5db4cd82ec68edf875eda)
https://yokinist.me/support-table
※ Dark mode is not supported in this PR
> feat: Support Notion table

- .github/workflows/docker-ghcr.yaml
- Dockerfile
- README.md
auto build docker image and push to ghcr
> Use Github Action auto build docker image 

- Dockerfile
Unessosary PAGE ID included in docker file
> Removed unknown PAGE ID

- layouts/layout.js
- package.json
- yarn.lock
- Upgrade `notion-client`, `notion-utils`, `react-notion-x` to `6.16.0`
- Add a new component `Pdf` to `NotionRenderer`
> Upgrade dependencies

- components/Comments.js
Fix the comment component's style issue.
before:
after:
> Fix: add styles to comment component

- blog.config.js
- components/BlogPost.js
- components/Container.js
- components/FormattedDate.js
- components/Post.js
- lib/date.js
- lib/dayjs.js
- lib/formatDate.js
- lib/notion/filterPublishedPosts.js
- lib/notion/getAllPosts.js
- lib/rss.js
- next.config.js
- package.json
- pnpm-lock.yaml
> feat: Refactor Date Handling Functionality
